### ISSUE TITLE
Topic Modeling Bug

### ISSUE THREAD

**Issue by zjafri08** [mfligiel/Capstone_Text_Mining#1]
I am running into an error when applying this function to the Lityx keywords. I suspect that some of the keywords are not yielding string values after cleaning, which is required. Below is the error which I will further investigate.

![image](https://user-images.githubusercontent.com/44909671/113341723-21feff80-92f3-11eb-9458-fa2d7ecf20b3.png)

**Comment by mfligiel** [comment]
How are keywords formatted?  Is it taking a series and not a list of strings maybe?

**Comment by zjafri08** [comment]
I'll try and test/troubleshoot to see if I can figure it out. It worked on a subset of the data but not the whole thing, so it leads me to believe there may an additional formatting step required for some of the data. I made some modification to the code for the function, so may have missed a step. Let's see what I come up with.

**Comment by zjafri08** [comment]
This was resolved.
